// Unique content for each service+location combo page
// Structured to avoid doorway page patterns — each has genuinely unique content

export interface ComboContent {
  serviceSlug: string;
  areaSlug: string;
  heroText: string;
  intro: string;
  localConsiderations: string[];
  detailedContent: string;
  projectHighlights: string[];
  whyUs: string;
}

export const COMBO_CONTENT: ComboContent[] = [
  // KITCHEN REMODELING
  {
    serviceSlug: "kitchen-remodeling",
    areaSlug: "wonder-lake",
    heroText: "Expert kitchen remodeling for Wonder Lake homeowners — from lakeside cottages to spacious family homes.",
    intro: "Wonder Lake kitchens come in all shapes and sizes, from cozy galley kitchens in lakefront cottages to expansive layouts in newer builds along Thompson Road and Highland Drive. As the local contractor based right here in Wonder Lake, we understand the unique character of homes in this community and design kitchen renovations that complement your home's style while maximizing functionality.",
    localConsiderations: [
      "Lakefront properties often have humidity considerations that affect material selection for cabinetry and countertops",
      "Many Wonder Lake homes built in the 1960s-1980s have outdated galley layouts perfect for open-concept conversions",
      "Seasonal lake living means kitchens need to handle entertaining — island seating and flow are key design priorities",
      "Older homes near the lake may require updated plumbing and electrical before cosmetic work begins",
    ],
    detailedContent: "Wonder Lake's housing stock ranges from charming mid-century homes near the lake to newer construction in surrounding subdivisions. Many homeowners come to us looking to update dated laminate countertops, replace particle-board cabinets with solid wood or plywood construction, and reconfigure closed-off kitchen layouts into open-concept spaces that connect to dining and living areas. We frequently work with Wonder Lake homeowners on kitchen islands — a feature many older homes lack — that add prep space, storage, and casual seating. Our team handles every aspect of the renovation including demolition, structural modifications for load-bearing wall removal, plumbing relocation, electrical panel upgrades, drywall, tile backsplashes, hardwood or LVP flooring, and final trim work. Because we're based in Wonder Lake, we're always nearby for quick consultations and responsive follow-up service.",
    projectHighlights: [
      "Open-concept kitchen conversion in a 1970s ranch home near Wonder Lake Beach",
      "Custom shaker cabinetry with quartz countertops for a family home on Highland Drive",
      "Complete kitchen gut-renovation with new plumbing and electrical in a lakefront property",
    ],
    whyUs: "As Wonder Lake residents ourselves, we treat every project like we're working on a neighbor's home — because we are. Our proximity means faster response times, easier scheduling, and a vested interest in maintaining our reputation right here in our own community.",
  },
  {
    serviceSlug: "kitchen-remodeling",
    areaSlug: "mchenry",
    heroText: "Professional kitchen remodeling in McHenry, IL — transforming kitchens across the Fox River Valley.",
    intro: "McHenry is one of McHenry County's most established communities, with a diverse housing stock that includes everything from historic downtown bungalows to modern homes in subdivisions like Chapel Hill, Lakemoor, and Boulder Ridge. Our kitchen remodeling services are tailored to the specific needs of McHenry homeowners, whether you're updating a builder-grade kitchen in a newer home or completely reimagining a kitchen in a century-old Craftsman.",
    localConsiderations: [
      "Downtown McHenry's older homes often have smaller kitchens that benefit from space-maximizing layouts and custom cabinetry",
      "Newer subdivision homes in McHenry frequently have builder-grade finishes that homeowners want to upgrade to premium materials",
      "Homes along the Fox River may have unique foundation and plumbing considerations during renovation",
      "McHenry's mix of architectural styles means kitchen designs need to complement the home's existing character",
    ],
    detailedContent: "McHenry homeowners frequently tell us their kitchens don't match the way they actually live. Builder-grade kitchens in newer subdivisions lack the storage, counter space, and premium finishes that families need, while older homes have cramped layouts that don't accommodate modern appliances. We address both scenarios with custom solutions. For newer homes, we typically upgrade countertops from laminate to quartz or granite, replace stock cabinets with soft-close custom cabinetry, add tile backsplashes, install under-cabinet lighting, and improve the kitchen's workflow with better layouts. For older McHenry homes, we often handle more extensive renovations that include moving walls, relocating plumbing, upgrading electrical service, installing new subflooring, and bringing everything up to current building codes. We work closely with McHenry Township building officials to ensure all permits and inspections are handled properly.",
    projectHighlights: [
      "Builder-grade to custom kitchen upgrade in a Chapel Hill subdivision home",
      "Full kitchen renovation with island addition in a downtown McHenry bungalow",
      "Modern farmhouse kitchen remodel with custom open shelving and apron-front sink",
    ],
    whyUs: "Just a short drive from our Wonder Lake headquarters, McHenry is one of our most active service areas. We've built strong relationships with local suppliers and inspectors, ensuring your kitchen remodel moves efficiently from start to finish.",
  },
  {
    serviceSlug: "kitchen-remodeling",
    areaSlug: "crystal-lake",
    heroText: "Stunning kitchen remodels in Crystal Lake, IL — where craftsmanship meets modern design.",
    intro: "Crystal Lake is known for its beautiful neighborhoods, excellent schools, and strong sense of community. Homeowners here take pride in their properties, and a kitchen remodel is one of the best investments you can make — both for your daily enjoyment and your home's resale value. From established neighborhoods like Lake in the Hills Shores and Country Club Estates to newer developments, we design and build kitchens that reflect Crystal Lake's high standards.",
    localConsiderations: [
      "Crystal Lake's competitive real estate market means kitchen remodels should maximize ROI with timeless design choices",
      "Many 1990s-2000s era homes in Crystal Lake subdivisions are due for their first major kitchen update",
      "Larger Crystal Lake homes often have formal dining rooms that homeowners want to integrate into an open kitchen concept",
      "Energy-efficient appliances and LED lighting are popular upgrades in this environmentally conscious community",
    ],
    detailedContent: "Crystal Lake homeowners typically have higher expectations for both design and execution, and we rise to that challenge on every project. We see a lot of demand for transitional and contemporary kitchen designs featuring shaker-style cabinetry in whites and grays, quartz countertops with waterfall edges, large-format porcelain tile backsplashes, and statement lighting over kitchen islands. Functional upgrades like pull-out pantry organizers, built-in spice racks, soft-close drawers, and dedicated charging stations are popular additions. Many Crystal Lake projects involve removing the wall between the kitchen and a formal dining room to create a large, open entertaining space. These structural modifications require careful engineering, temporary support installation, and coordination between our framing, electrical, plumbing, drywall, and finishing crews — all of which we manage in-house for quality control and scheduling efficiency. We also frequently incorporate butler's pantries, beverage stations, and second prep sinks in larger Crystal Lake kitchen remodels.",
    projectHighlights: [
      "Transitional kitchen with waterfall quartz island in a Country Club Estates home",
      "Open-concept kitchen and dining room conversion with custom built-in banquette",
      "Two-tone cabinetry kitchen remodel with integrated smart home appliances",
    ],
    whyUs: "Crystal Lake homeowners expect premium quality, and that's exactly what we deliver. Our attention to detail, material expertise, and project management ensure your kitchen remodel exceeds expectations — on time and on budget.",
  },
  {
    serviceSlug: "kitchen-remodeling",
    areaSlug: "woodstock",
    heroText: "Kitchen remodeling in Woodstock, IL — honoring your home's character with modern functionality.",
    intro: "Woodstock's historic square and charming residential streets are home to some of McHenry County's most character-rich properties. From Victorian-era homes near the town square to mid-century ranches and newer construction, Woodstock kitchens deserve renovations that respect their architectural heritage while delivering modern performance. Our team has extensive experience working with older homes and understands the unique challenges they present.",
    localConsiderations: [
      "Historic Woodstock homes near the square may have original plaster walls, knob-and-tube wiring, or galvanized plumbing that needs updating",
      "Preserving architectural character while modernizing is a priority for many Woodstock homeowners",
      "Older homes often have non-standard dimensions requiring custom cabinetry rather than stock sizes",
      "Woodstock's historic district may have additional considerations for exterior-facing changes visible from the street",
    ],
    detailedContent: "Woodstock's identity is rooted in its history — the town square, the Opera House, and streets lined with homes spanning more than a century of American architecture. When we remodel a kitchen in Woodstock, we take that context seriously. For historic homes, we often design kitchens that blend period-appropriate details like beadboard panels, furniture-style cabinet legs, and traditional hardware with modern conveniences like soft-close hinges, quartz countertops, and energy-efficient appliances. We're experienced with the challenges older homes present: leveling floors that have settled over decades, replacing outdated wiring and plumbing, reinforcing walls for heavy upper cabinets, and working around original architectural details worth preserving. For Woodstock's newer homes, we focus on upgrading builder-grade finishes to materials and designs that match the town's character-rich aesthetic. Craftsman-style and farmhouse-inspired kitchens are particularly popular here, featuring details like shiplap accent walls, apron-front sinks, open shelving, and natural wood elements that connect to Woodstock's small-town charm.",
    projectHighlights: [
      "Period-sensitive kitchen renovation in a 1920s Craftsman near the Woodstock Square",
      "Farmhouse kitchen remodel with reclaimed wood island and custom hood vent cover",
      "Complete kitchen modernization in a 1960s ranch with new layout and appliance integration",
    ],
    whyUs: "We understand that Woodstock homes aren't cookie-cutter, and neither are our kitchen designs. Our experience with older construction and custom solutions means your Woodstock kitchen remodel will be thoughtful, well-executed, and true to your home's character.",
  },
  {
    serviceSlug: "kitchen-remodeling",
    areaSlug: "lake-in-the-hills",
    heroText: "Modern kitchen remodeling in Lake in the Hills, IL — upgrading your home for the way you live today.",
    intro: "Lake in the Hills has seen tremendous growth over the past two decades, with many homes built between 2000 and 2015 now reaching the point where their original kitchens need refreshing. These homes often have solid bones and good layouts but feature dated finishes like oak cabinetry, laminate countertops, and basic tile backsplashes. Our kitchen remodeling services transform these spaces with premium materials and modern design while working within the home's existing footprint.",
    localConsiderations: [
      "Many Lake in the Hills homes are 15-25 years old with original builder-grade kitchens ready for their first major update",
      "Subdivision HOAs may have exterior modification guidelines, though interior kitchen remodels are typically unrestricted",
      "Open floor plans common in Lake in the Hills homes mean kitchen aesthetics need to coordinate with adjacent living spaces",
      "Growing families in this community prioritize durable, kid-friendly materials like quartz over marble",
    ],
    detailedContent: "Lake in the Hills is a family-oriented community where the kitchen truly is the center of daily life. We see a consistent pattern with homeowners here: they purchased homes with builder-grade kitchens that looked fine at first but have shown their limitations over time. Laminate countertops have chipped or stained, stock oak cabinets have dated the space, basic tile floors are cracked, and the generic lighting doesn't provide enough task illumination. Our approach for Lake in the Hills kitchens typically involves a comprehensive refresh: replacing all cabinetry with custom or semi-custom options in contemporary finishes (painted whites, grays, or navy are trending), installing quartz or granite countertops, adding designer tile backsplashes, upgrading to LED recessed and pendant lighting, installing luxury vinyl plank or porcelain tile flooring, and replacing all fixtures and hardware. Many homeowners also take this opportunity to upgrade appliances to stainless steel packages with features like French door refrigerators, double ovens, and induction cooktops. Because most Lake in the Hills homes have open floor plans, we ensure the kitchen design coordinates seamlessly with the adjacent living and dining areas.",
    projectHighlights: [
      "Complete builder-grade kitchen transformation with two-tone cabinetry and quartz countertops",
      "Kitchen remodel with expanded island and breakfast bar in a growing family's home",
      "Modern kitchen refresh with new cabinetry, backsplash, and smart appliance integration",
    ],
    whyUs: "We've remodeled kitchens throughout Lake in the Hills and understand the specific needs of homes in this community. Our familiarity with local suppliers and building requirements means a smoother, faster renovation process.",
  },

  // BATHROOM REMODELING
  {
    serviceSlug: "bathroom-remodeling",
    areaSlug: "wonder-lake",
    heroText: "Bathroom remodeling in Wonder Lake, IL — creating spa-like retreats in your own home.",
    intro: "Wonder Lake homeowners deserve bathrooms that are more than just functional — they should be personal retreats. Whether you're renovating a cramped hall bathroom in an older lakeside home or transforming a master bath into a luxury spa, our team delivers stunning results with premium materials and expert craftsmanship. We understand the specific challenges Wonder Lake homes present, from moisture management near the lake to updating aging plumbing systems.",
    localConsiderations: [
      "Lakefront properties require extra attention to moisture barriers and ventilation to prevent mold and mildew",
      "Many older Wonder Lake homes have cast iron drain pipes that should be replaced during renovation",
      "Small bathroom footprints in vintage lake homes benefit from space-saving designs like corner showers and wall-mounted vanities",
      "Well water common in parts of Wonder Lake can affect fixture selection — hard water-resistant finishes are recommended",
    ],
    detailedContent: "Bathroom remodels in Wonder Lake range from simple updates to complete gut renovations. Many of the older homes near the lake have original bathrooms with outdated tile, worn fixtures, and inefficient layouts. We frequently convert small tub-shower combos into spacious walk-in showers with frameless glass enclosures, replace pedestal sinks with vanities that add much-needed storage, install heated flooring for comfort during cold Illinois winters, and upgrade ventilation systems to handle the area's humidity. For master bathroom renovations, popular upgrades include freestanding soaking tubs, dual-sink vanities with quartz tops, large-format porcelain tile, rain shower heads, and built-in niches for toiletries. We handle all plumbing and electrical work in-house, ensuring everything is done to code and built to last.",
    projectHighlights: [
      "Master bath conversion from tub to walk-in shower with heated tile flooring",
      "Hall bathroom renovation with custom vanity and subway tile surround in a lakefront cottage",
      "ADA-compliant bathroom remodel with grab bars and barrier-free shower entry",
    ],
    whyUs: "Living and working in Wonder Lake means we're always close by. If a question or concern comes up during or after your bathroom remodel, we're just minutes away — not hours.",
  },
  {
    serviceSlug: "bathroom-remodeling",
    areaSlug: "mchenry",
    heroText: "Professional bathroom renovations in McHenry, IL — from quick refreshes to complete transformations.",
    intro: "McHenry's diverse housing stock means bathroom remodeling needs vary widely. Downtown homes may need full gut renovations to update decades-old bathrooms, while newer subdivision homes often just need upgraded finishes to replace builder-grade materials. Whatever your McHenry bathroom needs, we deliver custom solutions that elevate both form and function.",
    localConsiderations: [
      "Older McHenry homes near downtown may have original tile, plumbing, and subfloor that need replacement",
      "Two-story homes common in McHenry subdivisions often benefit from second-floor bathroom upgrades",
      "Homes along the Fox River should consider enhanced waterproofing in bathrooms",
      "Growing families in McHenry often need to convert a half bath into a full bath or add a second bathroom",
    ],
    detailedContent: "In McHenry, we see strong demand for both master bathroom transformations and functional family bathroom upgrades. Master bath projects typically involve removing existing tubs in favor of large walk-in showers with bench seating, frameless glass, and multiple shower heads. We install new vanities with soft-close drawers, quartz or marble countertops, and contemporary faucets. Flooring upgrades to large-format porcelain tile with radiant heating are extremely popular for McHenry's cold winters. For family bathrooms, durability and storage are priorities — we install solid surface countertops that resist staining, tiled tub surrounds that outlast acrylic inserts, and vanity towers or linen cabinets that keep towels and supplies organized. When McHenry homeowners need to add a bathroom — whether converting a closet into a half bath or finishing a basement bathroom — we handle the full scope including running new drain lines, water supply, venting, electrical, and all finishes.",
    projectHighlights: [
      "Luxury master bath with freestanding tub, walk-in shower, and dual vanity",
      "Family bathroom upgrade with tiled tub surround and storage tower",
      "Half-bath addition in a McHenry townhome utilizing unused closet space",
    ],
    whyUs: "McHenry is one of our most active service areas. We've developed efficient processes specifically for the types of homes common in this community, which means faster project timelines and fewer surprises.",
  },
  {
    serviceSlug: "bathroom-remodeling",
    areaSlug: "crystal-lake",
    heroText: "Luxury bathroom remodeling in Crystal Lake, IL — spa-quality design and construction.",
    intro: "Crystal Lake homeowners consistently seek bathroom remodels that rival high-end spa experiences. The community's well-maintained homes and strong property values make premium bathroom renovations a smart investment. We design and build bathrooms that combine luxury materials, thoughtful layouts, and impeccable craftsmanship to create spaces you'll enjoy every day.",
    localConsiderations: [
      "Crystal Lake's higher home values justify premium bathroom finishes that maximize both enjoyment and resale value",
      "Many two-story Crystal Lake homes have master suites that benefit from expanded bathroom footprints",
      "Water heater capacity should be evaluated when adding features like rain showers or soaking tubs",
      "Crystal Lake homeowners frequently request smart bathroom features like heated mirrors and digital shower controls",
    ],
    detailedContent: "Our Crystal Lake bathroom projects frequently push the boundaries of residential bathroom design. We've installed zero-threshold showers with linear drains and full-wall porcelain slabs, freestanding tubs positioned beneath statement chandeliers, floating vanities with integrated LED lighting, and heated towel bars recessed into tiled walls. Material selections in Crystal Lake tend toward the premium end: natural stone, hand-glazed ceramic tile, solid wood vanities, and brushed gold or matte black fixtures. We also see strong interest in expanding bathroom footprints by borrowing space from adjacent closets or bedrooms to create true master suites with separate shower and tub areas, dual vanities with a makeup station, and enclosed water closets. These projects require careful structural planning, plumbing engineering, and coordination between multiple trades — all of which we manage seamlessly.",
    projectHighlights: [
      "Spa-inspired master bath with curbless shower, soaking tub, and heated floors throughout",
      "His-and-hers vanity installation with custom mirrors and pendant lighting",
      "Complete master suite reconfiguration borrowing closet space for an expanded bathroom",
    ],
    whyUs: "Crystal Lake homeowners expect the best, and our portfolio of completed projects in this community demonstrates our ability to deliver luxury bathroom renovations that exceed expectations.",
  },
  {
    serviceSlug: "bathroom-remodeling",
    areaSlug: "woodstock",
    heroText: "Bathroom remodeling in Woodstock, IL — blending vintage charm with modern comfort.",
    intro: "Woodstock's character-rich homes deserve bathrooms that honor their architectural heritage while providing modern comfort and functionality. Whether you're working with an original bathroom in a historic home or updating a builder-grade space in a newer development, our bathroom remodeling services bring thoughtful design and quality construction to every Woodstock project.",
    localConsiderations: [
      "Historic Woodstock homes may have original hex tile, clawfoot tubs, or plaster walls worth preserving or referencing in new designs",
      "Older plumbing systems in Woodstock homes often need updating to support modern fixtures and water pressure requirements",
      "Bathroom ventilation upgrades are important in older homes that may lack adequate exhaust fans",
      "Period-appropriate design elements like subway tile, pedestal sinks, and chrome fixtures complement Woodstock's historic character",
    ],
    detailedContent: "Woodstock bathroom remodels require a nuanced approach. In the historic homes near the town square, we often design bathrooms that reference the home's era — classic subway tile with dark grout, pedestal or console sinks, vintage-style fixtures with modern internals, and hex or penny tile floors. We preserve and refinish original clawfoot tubs when they're in good condition, or source reproduction models that fit the home's character. Behind the walls, however, everything is brought fully up to date with new copper or PEX plumbing, proper venting, modern electrical with GFCI protection, cement board substrate, and quality waterproofing membranes. For Woodstock's newer homes, we lean into the farmhouse aesthetic that resonates with the community — shiplap accent walls, wood-look tile, matte black fixtures, and barn-door vanity mirrors. Every Woodstock bathroom we build combines the charm homeowners love with the performance and durability modern materials provide.",
    projectHighlights: [
      "Restoration-style bathroom in an 1890s Victorian with reproduction hex tile and clawfoot tub",
      "Modern farmhouse bathroom with wood-look tile, barn door, and freestanding tub",
      "Accessible bathroom conversion with roll-in shower for aging-in-place in a Woodstock ranch home",
    ],
    whyUs: "Our experience with both historic and modern construction makes us uniquely qualified for Woodstock's diverse housing stock. We know how to navigate the challenges of older homes while delivering beautiful, lasting results.",
  },
  {
    serviceSlug: "bathroom-remodeling",
    areaSlug: "lake-in-the-hills",
    heroText: "Bathroom remodeling in Lake in the Hills, IL — upgrading builder-grade to beautiful.",
    intro: "Most Lake in the Hills homes were built with bathrooms that met basic needs but lack the style, storage, and features today's homeowners want. Builder-grade vanities, fiberglass tub surrounds, basic ceramic tile, and minimal lighting are common starting points. Our bathroom remodeling services transform these spaces into beautiful, functional rooms with premium materials and smart design.",
    localConsiderations: [
      "Builder-grade fiberglass tub/shower units in Lake in the Hills homes are prime candidates for tiled replacements",
      "Many homes have dual-sink master vanities with dated countertops and stock mirrors ready for upgrade",
      "Second-floor bathrooms require careful attention to waterproofing to protect ceilings below",
      "Growing families often need more storage — we design vanities and built-ins that maximize every inch",
    ],
    detailedContent: "Lake in the Hills bathroom remodels follow a clear pattern: homeowners want to replace cheap builder materials with quality finishes that will last and look beautiful for years. We typically start by removing fiberglass tub/shower units and replacing them with tiled surrounds or frameless glass walk-in showers. Stock vanities are swapped for custom or semi-custom cabinetry with soft-close doors and drawers, topped with quartz countertops. We replace basic plate mirrors with framed mirrors or medicine cabinets, upgrade lighting from single vanity bars to layered schemes with recessed lights, sconces, and decorative fixtures, and install new flooring — typically large-format porcelain tile or luxury vinyl plank. Many Lake in the Hills homeowners also add features like heated floors, towel warmers, and improved ventilation. For master bathrooms, we frequently expand the shower by eliminating the separate tub — a trade many homeowners are happy to make for a more spacious, luxurious shower experience.",
    projectHighlights: [
      "Builder-grade to luxury master bath transformation with walk-in shower and double vanity",
      "Kids' bathroom renovation with durable finishes, tiled tub surround, and ample storage",
      "Powder room upgrade with statement wallpaper, vessel sink, and designer lighting",
    ],
    whyUs: "We've completed numerous bathroom renovations in Lake in the Hills neighborhoods and know exactly what upgrades deliver the best combination of daily enjoyment and long-term value.",
  },

  // WHOLE HOUSE REMODELING
  {
    serviceSlug: "whole-house-remodeling",
    areaSlug: "wonder-lake",
    heroText: "Whole house remodeling in Wonder Lake, IL — complete home transformations for lake-area living.",
    intro: "Wonder Lake's housing stock includes many homes that are structurally sound but aesthetically and functionally outdated. Whole house remodeling allows you to reimagine every room without the cost and hassle of buying new. As the local contractor, we've transformed dozens of Wonder Lake homes from top to bottom, coordinating every trade from framing to finish carpentry.",
    localConsiderations: [
      "Lakefront properties may need foundation evaluation and moisture mitigation as part of a whole-house project",
      "Many 1960s-1980s Wonder Lake homes have aluminum wiring, galvanized plumbing, or asbestos materials requiring professional remediation",
      "Seasonal residents may want to upgrade insulation, windows, and HVAC for year-round comfort",
      "Open floor plans are highly desired in Wonder Lake — many older homes benefit from wall removal and layout reconfiguration",
    ],
    detailedContent: "A whole house remodel in Wonder Lake typically addresses everything from the foundation up. We start with a thorough assessment of the home's systems — electrical, plumbing, HVAC, insulation, and structural integrity. Many older Wonder Lake homes need panel upgrades from 100 to 200 amps, copper or PEX plumbing to replace galvanized pipes, and new insulation to meet current energy codes. Once the bones are solid, we move to the fun stuff: opening up floor plans by removing non-load-bearing walls (or properly engineering around load-bearing ones), installing new flooring throughout, replacing all interior doors and trim, updating every bathroom and the kitchen, painting every surface, and adding finishing touches like crown molding, wainscoting, and built-in shelving. The result is a home that feels brand new while retaining the location and lot you love. We manage every aspect of the project so you have a single point of contact throughout the process.",
    projectHighlights: [
      "Complete renovation of a 1970s lakefront ranch — new kitchen, baths, flooring, electrical, and open floor plan",
      "Fixer-upper transformation including remediation, new windows, and full interior redesign",
      "Seasonal cottage converted to year-round home with insulation upgrade, new HVAC, and modern finishes",
    ],
    whyUs: "Nobody knows Wonder Lake homes better. We've worked on properties throughout the community and understand the common issues and opportunities specific to homes in this area.",
  },
  {
    serviceSlug: "whole-house-remodeling",
    areaSlug: "mchenry",
    heroText: "Complete home renovations in McHenry, IL — reimagine every room in your home.",
    intro: "McHenry homeowners investing in whole house remodeling are making a smart decision. Whether you've purchased a fixer-upper along the Fox River, inherited a family home that needs modernizing, or simply want to bring your entire home up to date, our comprehensive renovation services handle every aspect of the transformation.",
    localConsiderations: [
      "Homes near the Fox River may have experienced past water damage requiring thorough inspection and remediation",
      "McHenry's mix of home ages means whole-house projects range from cosmetic refreshes to complete gut renovations",
      "Zoning and setback requirements should be verified if the remodel includes any footprint changes",
      "Energy efficiency upgrades are particularly impactful in McHenry's older homes — new windows, insulation, and HVAC can significantly reduce utility costs",
    ],
    detailedContent: "McHenry whole house remodels require careful planning and sequencing. We typically begin with a detailed scope meeting where we walk through every room and document your vision, priorities, and budget parameters. From there, we develop a phased plan that addresses systems first (electrical, plumbing, HVAC), then structural modifications, followed by rough-in work, and finally finishes. This approach ensures the home is safe and functional at every stage. Common elements in our McHenry whole-house projects include complete kitchen and bathroom renovations, hardwood or LVP flooring throughout, new interior doors and trim packages, fresh drywall where needed, whole-house painting, updated lighting fixtures, and improved storage solutions. We also frequently handle exterior improvements like new siding, windows, entry doors, and deck construction as part of the overall project. Our project management system keeps you informed with regular updates, and we maintain a clean, organized job site throughout the renovation.",
    projectHighlights: [
      "Historic McHenry home completely renovated with modern systems and period-appropriate finishes",
      "Ranch-to-open-concept transformation with new kitchen, flooring, and master suite upgrades",
      "Investment property renovation — full gut and rebuild of a neglected McHenry foreclosure",
    ],
    whyUs: "McHenry's proximity to our headquarters means we can have crews on-site daily and manage your project with the close attention it deserves.",
  },
  {
    serviceSlug: "whole-house-remodeling",
    areaSlug: "crystal-lake",
    heroText: "Premium whole house remodeling in Crystal Lake, IL — elevating your entire home.",
    intro: "Crystal Lake's established neighborhoods are filled with homes that have excellent bones and great locations but need comprehensive updating to meet today's standards. Our whole house remodeling services transform these properties into modern showpieces while preserving the qualities that make Crystal Lake such a desirable place to live.",
    localConsiderations: [
      "Crystal Lake's strong resale market means whole-house renovations should use design choices with broad appeal",
      "Many Crystal Lake homes have formal living and dining rooms that homeowners prefer to reconfigure into more usable spaces",
      "Property values in Crystal Lake support premium renovation investments with strong ROI",
      "Coordination with HOA guidelines may be required for exterior modifications in some Crystal Lake subdivisions",
    ],
    detailedContent: "Whole house remodeling in Crystal Lake is about creating a cohesive, elevated living experience throughout the entire home. We work with homeowners to develop a unified design language — consistent flooring, complementary color palettes, matching hardware and fixtures — that ties every room together. This design-forward approach is what separates a thoughtful renovation from a piecemeal update. Our Crystal Lake whole-house projects frequently include gourmet kitchen renovations, spa-inspired master bathrooms, open-concept living areas with built-in entertainment centers, home office spaces with custom millwork, mudrooms with cubbies and bench seating, laundry room upgrades, and finished basements. We handle all structural work, mechanical systems, and finishes with our own skilled crews, maintaining quality control and communication throughout. Many homeowners choose to live off-site during comprehensive renovations, and we coordinate timelines to minimize the disruption period.",
    projectHighlights: [
      "Comprehensive renovation of a 4-bedroom Colonial with designer finishes throughout",
      "Open-concept conversion with custom built-ins, new kitchen, and refinished hardwood floors",
      "Executive home refresh — updated every surface, fixture, and finish throughout a 3,500 sq ft home",
    ],
    whyUs: "Our portfolio of completed projects in Crystal Lake speaks for itself. We understand the community's standards and consistently deliver renovations that enhance both livability and property value.",
  },
  {
    serviceSlug: "whole-house-remodeling",
    areaSlug: "woodstock",
    heroText: "Whole house remodeling in Woodstock, IL — preserving character, delivering modernity.",
    intro: "Woodstock's charming homes tell stories through their architecture — from Victorian details to Craftsman woodwork to mid-century simplicity. Whole house remodeling in Woodstock is about honoring those stories while writing new chapters of comfort, efficiency, and modern living. Our team approaches every Woodstock renovation with respect for the home's heritage and excitement for its future.",
    localConsiderations: [
      "Historic homes near the Woodstock Square may have preservation guidelines affecting exterior renovations",
      "Older Woodstock homes frequently need complete electrical system replacement for safety and capacity",
      "Original hardwood floors in many Woodstock homes can often be refinished rather than replaced — we assess and advise",
      "Woodstock's older homes may have lead paint, asbestos, or other materials requiring professional handling",
    ],
    detailedContent: "Woodstock whole house remodels are some of our most rewarding projects because the results are so dramatic. We've taken homes with knob-and-tube wiring, galvanized plumbing, single-pane windows, and decades of deferred maintenance and transformed them into modern, efficient, beautiful homes — all while preserving the original character details that make them special. Our approach starts with a comprehensive assessment: What needs to be brought up to code? What original features are worth preserving? Where can we improve the layout without compromising structural integrity? We then develop a detailed plan that addresses safety and systems first, followed by layout modifications, and finally finishes and details. In Woodstock, we frequently restore original hardwood floors, preserve decorative trim and built-ins, and design new elements that complement the home's architectural style. The end result is a home that looks and feels like it's been lovingly maintained for a century — with all the modern comforts hidden behind the charm.",
    projectHighlights: [
      "Complete renovation of an 1890s Victorian — new systems, restored woodwork, modern kitchen and baths",
      "Mid-century ranch modernization with open floor plan, new windows, and contemporary finishes",
      "Whole-house renovation of a Craftsman bungalow preserving original built-ins and millwork details",
    ],
    whyUs: "Our experience with Woodstock's historic homes gives us a unique perspective on how to modernize without losing character. We see renovation as preservation and improvement working together.",
  },
  {
    serviceSlug: "whole-house-remodeling",
    areaSlug: "lake-in-the-hills",
    heroText: "Whole house remodeling in Lake in the Hills, IL — transforming your home from top to bottom.",
    intro: "Lake in the Hills homes built in the early 2000s are reaching the age where a comprehensive update makes sense. Original carpet is worn, paint colors are dated, kitchens and bathrooms need refreshing, and homeowners want their spaces to reflect current design trends and their family's evolving needs. Our whole house remodeling services address everything at once for a cohesive, efficient transformation.",
    localConsiderations: [
      "Lake in the Hills homes typically have good structural bones that make whole-house cosmetic and fixture updates very cost-effective",
      "Open floor plans in newer homes simplify some renovation aspects but require cohesive design choices visible across multiple rooms",
      "Basement finishing is a popular add-on for Lake in the Hills whole-house projects — many homes have unfinished lower levels",
      "Energy efficiency upgrades like new windows and improved insulation deliver strong returns in this community",
    ],
    detailedContent: "Whole house remodeling in Lake in the Hills is often about taking a solid, well-built home and elevating every surface, fixture, and finish to premium quality. These projects typically include replacing all flooring with hardwood, LVP, or tile, painting the entire interior, updating all lighting fixtures, renovating the kitchen with new cabinetry, countertops, and appliances, remodeling all bathrooms with new tile, vanities, and fixtures, replacing interior doors and adding new trim and molding details, and finishing basements to add usable living space. Because Lake in the Hills homes tend to have straightforward construction (wood-frame, standard layouts, accessible mechanicals), these renovations move efficiently. We can typically complete a comprehensive whole-house renovation in 8-16 weeks depending on scope. Our systematic approach — working room by room while managing shared systems like plumbing and electrical in coordinated phases — minimizes disruption and keeps the project on schedule.",
    projectHighlights: [
      "Complete 3,200 sq ft home renovation — every room updated with modern finishes and fixtures",
      "Whole-house remodel with finished basement addition including wet bar and home theater",
      "Family home transformation with updated kitchen, baths, flooring, and new paint throughout",
    ],
    whyUs: "Our efficiency with Lake in the Hills home styles means faster timelines and better value. We know these homes, and we know how to transform them beautifully.",
  },

  // HOME ADDITIONS
  {
    serviceSlug: "home-additions",
    areaSlug: "wonder-lake",
    heroText: "Home additions in Wonder Lake, IL — expanding your living space without leaving the lake.",
    intro: "Wonder Lake is a special place to live, and many homeowners would rather expand their current home than move away from the lake. Home additions let you add the space you need — whether it's an extra bedroom, expanded living area, sunroom, or in-law suite — while staying in the community you love. As local builders, we navigate Wonder Lake's zoning, setbacks, and building requirements with ease.",
    localConsiderations: [
      "Lakefront lot setback requirements must be verified before planning any addition footprint",
      "Foundation options may be affected by soil conditions and water table levels near Wonder Lake",
      "Additions should be designed to complement the home's existing roofline and architectural style",
      "Septic system capacity should be evaluated when adding bedrooms or bathrooms to Wonder Lake homes not on municipal sewer",
    ],
    detailedContent: "Wonder Lake home additions require thoughtful planning around lot constraints, zoning regulations, and the desire to maintain lake views or waterfront character. We begin every project with a site evaluation to determine what's possible within your lot's setback requirements, easements, and any lakefront restrictions. From there, we work with you to design an addition that maximizes the new space while integrating seamlessly with your existing home. Common Wonder Lake additions include sunrooms and three-season rooms that capitalize on lake views, family room extensions, master suite additions, and in-law apartments for multi-generational living. We handle everything from architectural drawings and permit applications through foundation work, framing, roofing, siding, windows, mechanical systems, insulation, drywall, and all interior finishes. The finished addition matches your existing home's exterior materials, roofline, and interior finishes so closely that it looks like it was always part of the original plan.",
    projectHighlights: [
      "Four-season sunroom addition overlooking Wonder Lake with heated floors and panoramic windows",
      "Master bedroom suite addition with walk-in closet and en-suite bathroom",
      "Attached garage conversion to in-law suite with kitchenette and accessible bathroom",
    ],
    whyUs: "We understand Wonder Lake's zoning and building requirements inside and out. Our local expertise means your addition project starts right and finishes strong.",
  },
  {
    serviceSlug: "home-additions",
    areaSlug: "mchenry",
    heroText: "Home additions in McHenry, IL — more space for your growing family.",
    intro: "McHenry families outgrow their homes but love their neighborhoods. Home additions solve that problem by expanding your living space right where you are. Whether you need an extra bedroom, a family room extension, a second-story addition, or a dedicated home office, our construction team designs and builds additions that blend perfectly with McHenry's diverse architectural styles.",
    localConsiderations: [
      "McHenry Township building department requires permits for all structural additions — we handle the full process",
      "Lot coverage ratios and setback requirements vary by McHenry zoning district and must be verified before design",
      "Some McHenry neighborhoods have architectural review processes for additions visible from the street",
      "Foundation design depends on local soil conditions — frost footings must extend below the 42-inch frost line in McHenry County",
    ],
    detailedContent: "Home additions in McHenry span a wide range of scope and complexity. On the simpler end, we build bump-outs that extend a kitchen or master bedroom by 100-200 square feet — enough to add a breakfast nook, walk-in closet, or expanded bathroom. Mid-range projects include full room additions that add 300-600 square feet for new bedrooms, family rooms, or home offices. On the larger end, we construct second-story additions that can double a ranch home's square footage, providing multiple bedrooms and bathrooms upstairs while preserving the main floor layout. Every McHenry addition project follows a disciplined process: site survey and zoning verification, architectural design, structural engineering, permit applications, foundation excavation and pouring, framing, roofing, exterior finishing to match existing materials, rough-in of plumbing, electrical, and HVAC, insulation, drywall, and all interior finishes including flooring, trim, paint, and fixtures. We coordinate inspections at every required stage and deliver a finished space that passes final inspection and exceeds your expectations.",
    projectHighlights: [
      "Second-story addition adding three bedrooms and two bathrooms to a McHenry ranch",
      "Family room addition with cathedral ceiling, fireplace, and French doors to patio",
      "Home office addition with built-in bookshelves and separate exterior entrance",
    ],
    whyUs: "Our experience building additions throughout McHenry means we anticipate challenges before they become problems. We work within local regulations and deliver additions that add real value to your home.",
  },
  {
    serviceSlug: "home-additions",
    areaSlug: "crystal-lake",
    heroText: "Custom home additions in Crystal Lake, IL — designed to enhance your home and lifestyle.",
    intro: "Crystal Lake's desirable location and strong home values make building an addition a smart investment. Rather than navigating Crystal Lake's competitive real estate market for a larger home, many families choose to add on to their current property. Our home addition services deliver custom-designed, expertly built spaces that increase your square footage, improve your floor plan, and boost your property value.",
    localConsiderations: [
      "Crystal Lake building department has specific requirements for additions — we manage all permits and inspections",
      "Property values in Crystal Lake support higher-end addition investments with excellent ROI",
      "Homeowner association rules in some Crystal Lake subdivisions may regulate addition design, materials, and placement",
      "Crystal Lake's excellent school districts make family-oriented additions (bedrooms, playrooms) especially valuable",
    ],
    detailedContent: "Crystal Lake home additions are investments in both quality of life and property value. We approach each project with a design-first mentality, ensuring the new space enhances the home's overall flow and curb appeal rather than looking like an afterthought. Our architectural design process considers sight lines from the street, roofline integration, window placement for natural light, and interior traffic flow between existing and new spaces. Popular additions in Crystal Lake include master suite expansions with luxury bathrooms and walk-in closets, great room additions with vaulted ceilings and built-in entertainment centers, gourmet kitchen extensions with breakfast rooms, mudroom and laundry room combinations at rear entries, and finished bonus rooms over garages. We use materials that match or exceed the quality of the existing home — matching brick, stone, or siding on the exterior, and coordinating flooring, trim profiles, and paint throughout the interior. The transition between old and new should be invisible to anyone who doesn't know it's there.",
    projectHighlights: [
      "Great room addition with vaulted ceiling and stone fireplace for a Crystal Lake colonial",
      "Master suite wing addition including bedroom, walk-in closet, and spa bathroom",
      "Kitchen extension with breakfast room, mudroom, and laundry room in a growing family's home",
    ],
    whyUs: "We build additions in Crystal Lake that look like they've always been part of the home. Our commitment to design integration and premium construction sets us apart.",
  },
  {
    serviceSlug: "home-additions",
    areaSlug: "woodstock",
    heroText: "Home additions in Woodstock, IL — expanding thoughtfully, building beautifully.",
    intro: "Adding on to a Woodstock home requires sensitivity to architectural context. Whether your home is a Victorian near the square, a Craftsman bungalow on a tree-lined street, or a ranch in a newer section of town, our additions are designed to complement and enhance the existing architecture. We build additions that respect what makes your home — and Woodstock — special.",
    localConsiderations: [
      "Homes in Woodstock's historic areas may have additional design review requirements for visible additions",
      "Matching existing architectural details like brackets, trim profiles, and window styles is critical for character homes",
      "Woodstock's older lots may have mature trees, gardens, or other features that influence addition placement",
      "Foundation work in Woodstock must account for local soil conditions and the 42-inch frost line requirement",
    ],
    detailedContent: "Woodstock home additions demand architectural sensitivity that not every contractor can provide. We invest significant effort in the design phase, studying the home's existing architectural language — roof pitch, eave depth, window proportions, siding profile, trim details — and replicating those elements in the addition. For a Victorian home, this might mean custom millwork, decorative brackets, and multi-light windows. For a Craftsman, it could include tapered columns, exposed rafter tails, and natural wood elements. For a ranch, clean lines, large windows, and a seamless roofline extension. Beyond aesthetics, Woodstock additions must be practical and well-built. We engineer foundations for McHenry County's freeze-thaw cycles, frame walls and roofs to handle Illinois snow loads, insulate to current energy codes, and install mechanical systems that integrate with the home's existing HVAC, plumbing, and electrical. The result is an addition that looks like it's been part of the home since day one and performs flawlessly for decades.",
    projectHighlights: [
      "Period-appropriate addition to a Craftsman bungalow including new family room and covered porch",
      "Sunroom addition with custom millwork matching a Victorian home's original trim details",
      "Master suite addition on a ranch home with new roofline that extends the existing profile seamlessly",
    ],
    whyUs: "Our appreciation for Woodstock's architectural heritage, combined with our construction expertise, ensures your addition enhances both your home and the neighborhood's character.",
  },
  {
    serviceSlug: "home-additions",
    areaSlug: "lake-in-the-hills",
    heroText: "Home additions in Lake in the Hills, IL — adding the space your family needs.",
    intro: "Lake in the Hills families frequently outgrow their homes as children get older, parents move in, or work-from-home needs evolve. Rather than uprooting from a community with great schools, parks, and neighbors, a well-designed home addition gives you the space you need right where you want to be. We build additions that look like they were part of the original home and function perfectly for your family's needs.",
    localConsiderations: [
      "Lake in the Hills subdivision lot sizes and setbacks determine the maximum addition footprint — we verify before designing",
      "HOA architectural review may be required for additions in some Lake in the Hills communities",
      "Many Lake in the Hills homes have unfinished basements that offer significant expansion potential without building out",
      "Second-story additions are possible on many Lake in the Hills ranch homes, though structural evaluation is required first",
    ],
    detailedContent: "Lake in the Hills home additions are driven by practical needs: growing families need more bedrooms, remote workers need dedicated offices, aging parents need in-law suites, and active families need more living space. We design additions around how your family actually lives. Need a first-floor master suite so you don't have to climb stairs? We can add one off the back of the home with a full bathroom, walk-in closet, and private patio access. Want a bonus room over the garage for a teen hangout or home gym? We can engineer the structural support and build a comfortable, finished space. Need a home office that's truly separate from family living areas? We can build a bump-out addition with its own entrance, built-in desk and shelving, and proper lighting and technology infrastructure. We also frequently finish basements as part of comprehensive Lake in the Hills home expansion projects — adding family rooms, bedrooms, bathrooms, wet bars, and home theaters below grade for maximum square footage without expanding the home's footprint.",
    projectHighlights: [
      "First-floor master suite addition allowing aging-in-place for a Lake in the Hills couple",
      "Bonus room addition over garage for a growing family — used as playroom and homework space",
      "Home office addition with separate entry, built-in cabinetry, and fiber internet connection",
    ],
    whyUs: "We understand Lake in the Hills families and what they need from their homes. Our additions are designed for real life, built to last, and priced fairly.",
  },

  // NEW HOME CONSTRUCTION
  {
    serviceSlug: "new-home-construction",
    areaSlug: "wonder-lake",
    heroText: "Custom new home construction in Wonder Lake, IL — build your dream home on the lake or in the countryside.",
    intro: "Wonder Lake offers some of McHenry County's most desirable building lots, from waterfront parcels with lake views to spacious rural properties surrounded by nature. If you've found the perfect lot in Wonder Lake, Perezidential Construction can build the custom home you've been dreaming of — designed around your lifestyle, built with quality materials, and finished with the craftsmanship that comes from a builder who lives in and loves this community.",
    localConsiderations: [
      "Lakefront lots in Wonder Lake have specific setback requirements and may require elevated foundations or flood zone compliance",
      "Soil conditions near the lake can affect foundation design — pier, crawlspace, or full basement options should be evaluated",
      "Well and septic systems are common in parts of Wonder Lake and must be properly designed for the home's size and occupancy",
      "Wonder Lake's natural beauty means new homes should be designed to take advantage of views and integrate with the landscape",
    ],
    detailedContent: "Building a new home in Wonder Lake is an opportunity to create something truly special. Whether you're planning a lakefront retreat with panoramic water views, a spacious ranch on a rural lot, or a modern farmhouse on acreage, our team handles every phase of construction from foundation to final walkthrough. Owner Steven Perez personally oversees every new home build, applying his deep knowledge of construction trades to ensure every system — framing, plumbing, electrical, HVAC, insulation — works together for maximum performance and longevity. We work with your architect or help you develop a custom floor plan that fits your lot, your budget, and your lifestyle. Our new home builds include complete site preparation, foundation work, structural framing, roofing, exterior finishing (siding, stone, brick), window and door installation, all mechanical systems, insulation to exceed energy codes, drywall, flooring, cabinetry, countertops, trim, paint, and final grading with landscaping preparation.",
    projectHighlights: [
      "Custom 3-bedroom ranch home on a lakefront lot with full walkout basement and covered deck",
      "Modern farmhouse new build on 2 acres with open floor plan and 3-car attached garage",
      "Energy-efficient new construction with spray foam insulation, high-efficiency HVAC, and triple-pane windows",
    ],
    whyUs: "As Wonder Lake residents, we build homes here like we're building for ourselves — because this is our community too. Our local knowledge of lots, soil conditions, and building requirements gives you a significant advantage.",
  },
  {
    serviceSlug: "new-home-construction",
    areaSlug: "mchenry",
    heroText: "New home construction in McHenry, IL — quality custom homes built from the ground up.",
    intro: "McHenry continues to grow, with new lots and infill opportunities available throughout the area. Whether you're building on a vacant lot, replacing a teardown, or developing a subdivision parcel, Perezidential Construction delivers custom new home construction with the quality and attention to detail that McHenry families deserve. We handle every aspect of the build from permits to punchlist.",
    localConsiderations: [
      "McHenry Township has specific building codes and permit requirements for new construction that we navigate daily",
      "Lot grading and drainage plans are required by McHenry building department and must be professionally prepared",
      "Impact fees and utility connection charges vary by location within McHenry and should be budgeted early",
      "McHenry's diverse neighborhoods mean new homes should be designed to complement surrounding architecture",
    ],
    detailedContent: "New home construction in McHenry gives you the freedom to design exactly the home you want, built to today's codes and energy standards. We construct homes ranging from efficient starter homes to large custom estates, all built with the same commitment to quality. Our process begins with a thorough lot evaluation — we assess soil conditions, drainage, utility access, setback requirements, and any other factors that influence the build. From there, we work with you on architectural plans, material selections, and a detailed budget. During construction, we manage all trades, schedule inspections, and maintain constant communication so you always know where your project stands. Our new home builds in McHenry feature modern framing techniques, engineered lumber where appropriate, high-efficiency HVAC systems, PEX plumbing, 200-amp electrical service, spray foam or blown-in insulation, and premium interior finishes. We build homes that are comfortable, efficient, durable, and beautiful.",
    projectHighlights: [
      "Custom 4-bedroom colonial on an infill lot in established McHenry neighborhood",
      "Spec home build with open concept, granite kitchen, and finished basement",
      "Accessible ranch home designed for aging-in-place with wide doorways and zero-step entry",
    ],
    whyUs: "Our proximity to McHenry and established relationships with local officials, suppliers, and subcontractors mean your new home build runs smoothly from groundbreaking to move-in day.",
  },
  {
    serviceSlug: "new-home-construction",
    areaSlug: "crystal-lake",
    heroText: "Premium new home construction in Crystal Lake, IL — build the home Crystal Lake deserves.",
    intro: "Crystal Lake's desirable location, excellent schools, and strong community make it one of McHenry County's most sought-after addresses. Building a new custom home here is an investment in both lifestyle and long-term value. Perezidential Construction builds new homes in Crystal Lake that match the community's high standards — with premium materials, thoughtful design, and impeccable execution.",
    localConsiderations: [
      "Crystal Lake's competitive market and strong property values support premium new construction investments",
      "Some Crystal Lake subdivisions have architectural review committees with design guidelines for new builds",
      "Energy efficiency and sustainable building practices are increasingly important to Crystal Lake buyers",
      "Crystal Lake building department requires detailed plans and engineering for all new construction permits",
    ],
    detailedContent: "Building a new home in Crystal Lake means creating something exceptional. The community's high standards and strong property values demand quality construction and thoughtful design. We approach every Crystal Lake new build with a design-first mentality — considering curb appeal, interior flow, natural light, outdoor living connections, storage solutions, and technology integration from the earliest planning stages. Our Crystal Lake new homes feature premium specifications: solid wood or high-quality thermofoil cabinetry, quartz or granite countertops, hardwood and tile flooring, designer lighting packages, smart home pre-wiring, oversized garages with epoxy floors, and landscaped yards with irrigation systems. We also incorporate energy-efficient features like high-SEER HVAC systems, tankless water heaters, LED lighting throughout, Energy Star appliances, and enhanced insulation packages. The result is a home that's beautiful, comfortable, efficient, and built to maintain its value in Crystal Lake's strong real estate market.",
    projectHighlights: [
      "Custom 5-bedroom executive home with gourmet kitchen, home theater, and 4-car garage",
      "Contemporary new build with flat roof sections, floor-to-ceiling windows, and smart home integration",
      "Traditional colonial with wrap-around porch, finished basement, and professional landscaping",
    ],
    whyUs: "We build new homes in Crystal Lake that stand out — for their quality, their design, and their attention to every detail. Our commitment to excellence matches the community's expectations.",
  },
  {
    serviceSlug: "new-home-construction",
    areaSlug: "woodstock",
    heroText: "New home construction in Woodstock, IL — building homes with character for a town with character.",
    intro: "Woodstock's unique identity — rooted in history, community, and small-town charm — deserves new homes that contribute to rather than detract from its character. Whether you're building on a lot near the historic square or in a newer section of town, we design and construct homes that feel like they belong in Woodstock while delivering all the performance and comfort of modern construction.",
    localConsiderations: [
      "New construction near Woodstock's historic district should be architecturally sensitive to surrounding homes",
      "Woodstock's older infrastructure areas may have unique utility connection requirements",
      "Building lots in established Woodstock neighborhoods may be narrower or irregularly shaped, requiring creative floor plans",
      "Woodstock homebuyers often value character-rich architectural details like covered porches, dormers, and quality millwork",
    ],
    detailedContent: "New home construction in Woodstock is about more than just building walls and a roof — it's about creating a home that fits the community's character. We design Woodstock homes with architectural details that reference the town's heritage: covered front porches for waving at neighbors, quality millwork that echoes Craftsman and Victorian traditions, proportioned windows that look right on the street, and thoughtful landscaping that enhances curb appeal. Behind the character-rich exterior, every Woodstock home we build features modern construction techniques, current code compliance, efficient mechanical systems, and quality materials throughout. We're equally comfortable building a Craftsman bungalow on a small downtown lot or a spacious family home on acreage outside town. Owner Steven Perez's mastery of multiple trades ensures that every element — from the foundation to the ridge cap — is executed with care and built to last through Illinois' demanding climate.",
    projectHighlights: [
      "Craftsman-style new build on an infill lot with covered porch, custom millwork, and period-appropriate details",
      "Modern farmhouse on 3 acres with barn-style detached garage and wrap-around porch",
      "Energy-efficient ranch home with open floor plan, radiant floor heating, and solar-ready wiring",
    ],
    whyUs: "We appreciate what makes Woodstock special and build new homes that add to the community's character — not generic houses that could be anywhere.",
  },
  {
    serviceSlug: "new-home-construction",
    areaSlug: "lake-in-the-hills",
    heroText: "New home construction in Lake in the Hills, IL — modern homes for modern families.",
    intro: "Lake in the Hills continues to attract families looking for great schools, safe neighborhoods, and suburban convenience. New home construction here gives you the opportunity to build exactly the home your family needs — with the layout, features, and finishes you choose. Perezidential Construction builds new homes in Lake in the Hills that are designed for how families actually live, with quality construction that stands the test of time.",
    localConsiderations: [
      "Lake in the Hills has specific subdivision requirements and building codes that must be followed for new construction",
      "Many available lots in Lake in the Hills are in established subdivisions with HOA architectural guidelines",
      "Municipal water and sewer availability should be verified early — some parcels may require well and septic",
      "Lake in the Hills families prioritize features like mudrooms, home offices, and open-concept living — we design around real lifestyle needs",
    ],
    detailedContent: "New home construction in Lake in the Hills is about building smarter, not just bigger. Today's families need homes designed for their actual daily routines — drop zones by the garage entry for backpacks and sports gear, open kitchens that connect to family rooms for supervision and socializing, dedicated home office spaces with proper lighting and technology infrastructure, mudrooms with built-in storage, and flexible bonus rooms that evolve as kids grow. We design and build Lake in the Hills homes with these practical needs front and center, without sacrificing aesthetic appeal. Our standard specifications include quality cabinetry, quartz countertops, LVP or hardwood flooring in living areas, tiled bathrooms, recessed and pendant lighting, 200-amp electrical with USB outlets throughout, Cat6 wiring for home networking, and smart thermostat pre-wiring. We also offer upgrades like spray foam insulation, tankless water heaters, EV charging outlets in garages, and whole-house water filtration. Every home we build in Lake in the Hills is turnkey — move in and start living.",
    projectHighlights: [
      "4-bedroom new build with dedicated home office, mudroom, and finished basement rec room",
      "Open-concept family home with chef's kitchen, oversized island, and covered outdoor patio",
      "Duplex new construction designed as investment property with separate utilities and entries",
    ],
    whyUs: "We build homes in Lake in the Hills designed for real families — functional layouts, durable materials, and quality construction at a fair price.",
  },

  // ADU & GUEST HOUSE CONSTRUCTION
  {
    serviceSlug: "adu-guest-house-construction",
    areaSlug: "wonder-lake",
    heroText: "ADU and guest house construction in Wonder Lake, IL — maximize your property's potential.",
    intro: "Wonder Lake properties often feature generous lot sizes that are ideal for accessory dwelling units and guest houses. Whether you want a lakeside guest cottage for visitors, a detached home office surrounded by nature, a rental unit for supplemental income, or an in-law suite for aging parents, we design and build standalone structures that add value and functionality to your Wonder Lake property.",
    localConsiderations: [
      "Wonder Lake's larger lots typically have adequate space for ADU construction within setback requirements",
      "Septic system capacity must be evaluated when adding living units — existing systems may need upgrading",
      "Well water supply should be assessed to ensure adequate flow for an additional dwelling",
      "McHenry County zoning regulations for accessory structures vary by parcel classification — we verify before designing",
    ],
    detailedContent: "ADU and guest house construction in Wonder Lake takes advantage of the community's spacious lots and natural beauty. We build detached living units ranging from compact 400-square-foot studios to full 1,200-square-foot guest homes with one or two bedrooms, full kitchens, and bathrooms. Each unit is designed as a complete, self-contained living space with its own entrance, climate control, kitchen, bathroom, and utility connections. For Wonder Lake lakefront properties, we design guest houses that capture water views and complement the main home's architectural style. For rural lots, we create private retreats set apart from the main house with their own parking and outdoor spaces. We handle every aspect of ADU construction — zoning research, design, permitting, site preparation, foundation, framing, roofing, siding, mechanical systems, insulation, interior finishing, and final inspection. The finished unit is move-in ready and fully code-compliant.",
    projectHighlights: [
      "Detached guest cottage near Wonder Lake with kitchenette, full bath, and covered porch overlooking the water",
      "Garage conversion to in-law suite with accessible bathroom, small kitchen, and separate entrance",
      "Detached home office build with insulated walls, mini-split HVAC, and high-speed internet wiring",
    ],
    whyUs: "Wonder Lake's lot sizes make it ideal for ADU construction, and our local expertise with zoning, well/septic considerations, and building codes ensures your project gets approved and built right.",
  },
  {
    serviceSlug: "adu-guest-house-construction",
    areaSlug: "mchenry",
    heroText: "Guest house and ADU construction in McHenry, IL — additional living space on your property.",
    intro: "McHenry homeowners are increasingly recognizing the value of accessory dwelling units — whether for rental income, multi-generational living, or dedicated workspace. We build custom ADUs and guest houses throughout McHenry that are fully permitted, code-compliant, and designed to complement your existing home.",
    localConsiderations: [
      "McHenry Township zoning ordinances have specific requirements for accessory dwelling units including size limits and setbacks",
      "Properties on municipal water and sewer have simpler utility connections for ADUs than those on well and septic",
      "Parking requirements for ADUs may apply — we verify with McHenry building department during the design phase",
      "ADU designs should complement the main home's architecture for both aesthetics and potential resale value",
    ],
    detailedContent: "ADU construction in McHenry is growing in popularity as homeowners discover the flexibility these structures provide. We build ADUs that serve a wide range of purposes: rental units that generate passive income, in-law suites that keep extended family close while maintaining privacy, home offices that provide true separation from household activity, art studios with north-facing windows and specialized ventilation, and guest suites that give visitors their own private space. Our McHenry ADU builds are complete living spaces with full insulation, efficient heating and cooling (typically mini-split systems), plumbing for kitchens and bathrooms, 100-amp electrical service, fire-rated construction where required, and quality interior finishes including cabinetry, countertops, flooring, and paint. We design each ADU to complement the main home's exterior — matching or coordinating siding, roofing, window styles, and trim details so the property looks cohesive rather than pieced together.",
    projectHighlights: [
      "600 sq ft detached ADU with one bedroom, full kitchen, and laundry for rental income",
      "Above-garage apartment build with separate staircase entry and panoramic window",
      "In-law suite ADU with accessible design features, emergency call system, and covered walkway to main house",
    ],
    whyUs: "We navigate McHenry's ADU regulations efficiently, handle all permitting, and build units that add genuine value to your property.",
  },
  {
    serviceSlug: "adu-guest-house-construction",
    areaSlug: "crystal-lake",
    heroText: "ADU and guest house construction in Crystal Lake, IL — smart property investments.",
    intro: "Crystal Lake's strong property values make ADU construction a particularly smart investment. A well-built guest house or accessory dwelling unit adds usable space, rental income potential, and property value. We design and build Crystal Lake ADUs with the same quality and attention to detail as our full-scale home construction projects.",
    localConsiderations: [
      "Crystal Lake's higher property values mean ADU construction investments are well-supported by the market",
      "Some Crystal Lake subdivisions have HOA restrictions on accessory structures — we verify before proceeding",
      "Crystal Lake building department has specific ADU requirements including fire separation and egress standards",
      "Design quality matters in Crystal Lake — ADUs should feature premium finishes consistent with the community",
    ],
    detailedContent: "Crystal Lake ADUs and guest houses should reflect the community's standards for quality and design. We build ADUs in Crystal Lake that could stand alone as desirable living spaces — with quality cabinetry, solid surface countertops, tiled bathrooms, hardwood or LVP flooring, modern lighting, and efficient mechanical systems. Popular Crystal Lake ADU configurations include detached guest suites for visiting family, home offices for remote professionals who need true separation from household noise, pool houses with changing rooms and kitchenettes, and rental units designed to attract quality tenants. We handle the complete process from initial zoning verification through design, engineering, permitting, construction, and final certificate of occupancy. Every Crystal Lake ADU we build is designed to enhance — not detract from — the main property's appearance and value.",
    projectHighlights: [
      "Designer guest house with vaulted ceiling, full kitchen, and luxury bathroom finishes",
      "Professional home office ADU with conference area, powder room, and separate entrance for clients",
      "Pool house with changing room, outdoor shower, kitchenette, and half bathroom",
    ],
    whyUs: "We build Crystal Lake ADUs to the same standard as custom homes — because in this community, quality matters for both your enjoyment and your property value.",
  },
  {
    serviceSlug: "adu-guest-house-construction",
    areaSlug: "woodstock",
    heroText: "Guest house and ADU construction in Woodstock, IL — thoughtfully designed additional living spaces.",
    intro: "Woodstock's character-rich properties deserve ADUs and guest houses that complement their architectural heritage. We design accessory dwelling units for Woodstock homes that look like natural extensions of the property, with architectural details and materials that match or enhance the main home's style.",
    localConsiderations: [
      "Woodstock's historic areas may have additional design review requirements for new accessory structures",
      "Older Woodstock lots may have unique utility routing challenges that require creative solutions",
      "Matching architectural details like roof pitch, siding profile, and trim style is essential in character-rich neighborhoods",
      "Woodstock's zoning for accessory structures should be verified parcel-by-parcel as requirements may vary",
    ],
    detailedContent: "Building an ADU or guest house in Woodstock requires the same architectural sensitivity we bring to all our Woodstock projects. We study the main home's architectural language and design the ADU to speak the same vocabulary — matching roof pitch, complementing window proportions, using coordinating materials, and incorporating character details appropriate to the style. A guest house for a Victorian home might feature decorative trim and a covered porch, while one for a mid-century ranch would have clean lines and large windows. Beyond aesthetics, every Woodstock ADU we build is a fully functional, comfortable living space. We install proper insulation for year-round comfort, efficient mini-split heating and cooling, complete kitchen and bathroom facilities, adequate electrical service, and quality interior finishes. Foundation options include concrete slab, crawlspace, or full basement depending on the site and intended use. We manage all permitting and inspections through the Woodstock building department.",
    projectHighlights: [
      "Carriage house-style guest suite designed to complement an 1890s Victorian main home",
      "Artist's studio ADU with skylights, north-facing windows, and climate-controlled storage",
      "Multi-generational in-law suite with ADA-compliant design and private garden patio",
    ],
    whyUs: "Our understanding of Woodstock's architectural heritage means your ADU or guest house will look like it's always been part of the property — not an afterthought.",
  },
  {
    serviceSlug: "adu-guest-house-construction",
    areaSlug: "lake-in-the-hills",
    heroText: "ADU and guest house construction in Lake in the Hills, IL — practical spaces for modern needs.",
    intro: "Lake in the Hills homeowners are discovering that ADUs solve real problems — from housing aging parents nearby to creating income-producing rental units to building dedicated home offices. We construct accessory dwelling units in Lake in the Hills that are practical, attractive, and built to the same quality standards as our custom homes.",
    localConsiderations: [
      "Lake in the Hills HOA regulations may affect ADU placement, size, and exterior appearance",
      "Municipal utility connections for ADUs require coordination with the village",
      "ADU size limits and setback requirements in Lake in the Hills must be verified before design",
      "Many Lake in the Hills lots can accommodate ADUs but require careful placement for drainage and access",
    ],
    detailedContent: "ADU construction in Lake in the Hills addresses practical needs that many families face. Parents are aging and need to live nearby but want independence. Adult children need affordable housing while saving for their own home. Remote work is permanent but the kitchen table isn't a real office. Guests visit frequently but the pullout couch isn't cutting it anymore. We design Lake in the Hills ADUs for specific uses — each with features tailored to its purpose. Rental ADUs include separate utility meters, soundproofing, and durable finishes. In-law suites feature accessible design elements, emergency lighting, and proximity to the main house. Home offices include dedicated internet drops, proper task lighting, sound isolation, and client-appropriate finishes. Guest suites offer hotel-like amenities in a private, self-contained space. Whatever the purpose, every Lake in the Hills ADU we build is permitted, inspected, code-compliant, and finished to a standard you'd be proud to show anyone.",
    projectHighlights: [
      "Detached rental ADU generating $1,400/month income on a Lake in the Hills residential lot",
      "Connected in-law suite addition with private entrance, kitchenette, and ADA bathroom",
      "Detached home office with soundproofing, built-in desk, and video conferencing lighting",
    ],
    whyUs: "We build ADUs in Lake in the Hills that solve real problems for real families — practical, well-built, and designed for their specific intended use.",
  },

  // MODULAR & MANUFACTURED HOMES
  {
    serviceSlug: "modular-manufactured-homes",
    areaSlug: "wonder-lake",
    heroText: "Modular and manufactured home services in Wonder Lake, IL — affordable homeownership with quality construction.",
    intro: "Wonder Lake has a proud tradition of both site-built and manufactured housing. Perezidential Construction provides comprehensive modular and manufactured home services throughout the Wonder Lake area — from new installation and site preparation to renovations, additions, and upgrades for existing manufactured homes. We bring the same quality craftsmanship to manufactured home projects that we apply to all our construction work.",
    localConsiderations: [
      "Wonder Lake has multiple manufactured home communities and individual lots suitable for manufactured housing",
      "Foundation and anchoring requirements for manufactured homes in McHenry County must meet HUD and local codes",
      "Septic and well systems must be properly sized and connected for manufactured homes on private lots",
      "Skirting, siding, and exterior finishing are critical for both appearance and energy efficiency in Illinois weather",
    ],
    detailedContent: "Our manufactured and modular home services in Wonder Lake cover the full lifecycle. For new installations, we handle site clearing and grading, foundation preparation (concrete runners, pads, or full perimeter foundations), delivery coordination with the manufacturer, home set-up and leveling, utility hookups (water, sewer/septic, electric, gas), skirting installation, deck and porch construction, and final inspection. For existing manufactured homes, we provide renovation services including kitchen and bathroom remodels, flooring replacement, drywall repair and painting, window and door upgrades, roof-over installations, room additions, and deck construction. We also handle manufactured home repairs including water damage remediation, subfloor replacement, re-leveling, and foundation repairs. Owner Steven Perez's broad trade expertise is particularly valuable for manufactured home work, where understanding how the entire structure functions as a system leads to better outcomes.",
    projectHighlights: [
      "Complete manufactured home installation on private lot including foundation, utilities, and deck",
      "Kitchen and bathroom renovation in existing manufactured home with custom cabinetry and tile work",
      "Manufactured home addition — 12x20 sunroom with insulated walls and mini-split heating/cooling",
    ],
    whyUs: "We treat manufactured home projects with the same respect and quality as any other construction project. Your home is your home, regardless of how it was built.",
  },
  {
    serviceSlug: "modular-manufactured-homes",
    areaSlug: "mchenry",
    heroText: "Modular and manufactured home services in McHenry, IL — expert installation and renovation.",
    intro: "McHenry area homeowners with modular or manufactured homes deserve the same quality construction services as anyone else. Perezidential Construction provides professional manufactured home installation, renovation, and repair services throughout McHenry — treating every project with the care and craftsmanship it deserves.",
    localConsiderations: [
      "McHenry has manufactured home communities with specific rules about modifications and improvements",
      "McHenry Township building codes apply to manufactured home additions and significant modifications",
      "Energy upgrades like improved insulation and window replacement deliver exceptional value in manufactured homes",
      "Manufactured home renovations in McHenry should use materials rated for the home's specific construction type",
    ],
    detailedContent: "Manufactured and modular home services in McHenry encompass everything from turnkey new installations to targeted renovations that dramatically improve existing homes. For new modular home projects, we coordinate with manufacturers on timing and access, prepare the site with proper grading and foundation work, manage the set process, and complete all finishing work from utility connections to landscaping. For renovation projects on existing manufactured homes, we specialize in kitchen and bathroom remodels that maximize space and quality within the home's structure. We replace countertops, install custom-fit cabinetry, upgrade fixtures and appliances, install tile or LVP flooring, and improve lighting. We also handle structural improvements like reinforcing walls for mounted TVs or heavy cabinets, replacing soft subflooring, and improving insulation. Our manufactured home deck and porch construction adds outdoor living space and improves curb appeal — we build custom-designed wood and composite decks that properly attach to the home's structure and meet local codes.",
    projectHighlights: [
      "Modular home set and finish on prepared lot with full basement and attached garage",
      "Manufactured home kitchen gut-renovation with new layout, cabinetry, and quartz countertops",
      "Custom 16x24 composite deck with built-in seating and vinyl railing for manufactured home",
    ],
    whyUs: "We know manufactured home construction inside and out and bring genuine expertise — not guesswork — to every project in the McHenry area.",
  },
  {
    serviceSlug: "modular-manufactured-homes",
    areaSlug: "crystal-lake",
    heroText: "Modular and manufactured home services in Crystal Lake, IL — quality upgrades and professional installation.",
    intro: "Crystal Lake area homeowners with manufactured or modular homes can count on Perezidential Construction for professional installation, renovation, and improvement services. We elevate manufactured home living with quality materials, expert craftsmanship, and designs that maximize the home's potential.",
    localConsiderations: [
      "Crystal Lake area manufactured home communities may have specific improvement guidelines",
      "Modular homes in Crystal Lake should meet the same quality standards expected in the community",
      "Energy efficiency improvements are particularly impactful in manufactured homes and reduce monthly costs significantly",
      "Crystal Lake's building department may have specific requirements for manufactured home modifications",
    ],
    detailedContent: "Our Crystal Lake modular and manufactured home services focus on maximizing value and quality of life. For homeowners in manufactured homes, we provide renovation services that transform dated interiors into modern, attractive living spaces. Popular upgrades include replacing all flooring with durable LVP or tile, updating kitchens with new cabinetry and countertops, remodeling bathrooms with tiled showers and new vanities, replacing all lighting with modern LED fixtures, painting throughout, and improving insulation and weatherization. For new modular home installations in the Crystal Lake area, we manage the complete process from site evaluation and preparation through set-up, finishing, and final inspection. We ensure the finished product meets Crystal Lake's community standards and the homeowner's expectations. Our goal is to blur the line between manufactured and site-built — when we're done, your home should feel like a custom build.",
    projectHighlights: [
      "Complete interior renovation of double-wide manufactured home — new flooring, kitchen, baths, and paint",
      "Modular home installation with site-built garage attachment and professional landscaping",
      "Energy retrofit of manufactured home including new windows, insulation, and HVAC replacement",
    ],
    whyUs: "We bring Crystal Lake quality standards to every manufactured home project — because every homeowner deserves expert craftsmanship.",
  },
  {
    serviceSlug: "modular-manufactured-homes",
    areaSlug: "woodstock",
    heroText: "Modular and manufactured home services in Woodstock, IL — expert care for every type of home.",
    intro: "Woodstock's housing diversity includes manufactured and modular homes that deserve quality maintenance, renovation, and improvement services. Perezidential Construction serves Woodstock manufactured homeowners with the same dedication and craftsmanship we bring to every project — because a home is a home, and everyone deserves quality work.",
    localConsiderations: [
      "Woodstock area manufactured homes may have older construction that benefits from comprehensive updating",
      "Foundation inspection and re-leveling is important for long-term manufactured home performance in Woodstock's climate",
      "Woodstock's freeze-thaw cycles make proper skirting, insulation, and pipe protection critical for manufactured homes",
      "Manufactured home additions in the Woodstock area require permits and must meet local building codes",
    ],
    detailedContent: "Our Woodstock manufactured and modular home services address the full range of homeowner needs. For renovations, we transform dated manufactured home interiors with modern finishes — replacing old carpet with LVP flooring, updating kitchen cabinets and countertops, installing tiled tub surrounds and new vanities, and painting every surface for a fresh, clean look. We're experienced with the specific construction techniques used in manufactured homes, which differ from site-built homes in important ways. Wall studs may be 2x3 instead of 2x4, electrical boxes may be mounted differently, and plumbing access can be more limited. Our knowledge of these differences means we work efficiently and avoid the mistakes that general contractors unfamiliar with manufactured construction often make. For structural improvements, we handle re-leveling, subfloor replacement, roof repairs or roof-overs, window and door replacement, and foundation work. We also build additions, decks, porches, and carports that enhance living space and property value.",
    projectHighlights: [
      "Comprehensive renovation of 1990s single-wide including new flooring, kitchen, bathroom, and exterior skirting",
      "Room addition to manufactured home for expanded family room with cathedral ceiling effect",
      "Re-leveling, foundation repair, and new vinyl skirting for a Woodstock manufactured home",
    ],
    whyUs: "We understand manufactured home construction techniques and don't cut corners. Your Woodstock manufactured home gets the same quality attention as any project we take on.",
  },
  {
    serviceSlug: "modular-manufactured-homes",
    areaSlug: "lake-in-the-hills",
    heroText: "Modular and manufactured home services in Lake in the Hills, IL — upgrades that make a difference.",
    intro: "Lake in the Hills area homeowners with manufactured or modular homes deserve construction services delivered with expertise and respect. Perezidential Construction provides professional manufactured home installation, renovation, repair, and addition services that improve comfort, efficiency, and value.",
    localConsiderations: [
      "Lake in the Hills may have specific regulations for manufactured home placement and modification",
      "Manufactured homes in Lake in the Hills benefit significantly from insulation and window upgrades given Illinois weather",
      "Community rules in manufactured home parks may affect the scope of permitted exterior modifications",
      "Utility upgrade coordination with the village may be required for significant manufactured home improvements",
    ],
    detailedContent: "Our Lake in the Hills manufactured home services focus on practical improvements that make a real difference in daily life. We see homeowners who are tired of drafty windows, worn-out flooring, outdated kitchens, and bathrooms that feel cramped and dated. We solve these problems efficiently and affordably. Window replacement is one of our most impactful manufactured home upgrades — new vinyl windows with low-E glass dramatically reduce drafts, noise, and energy bills. Kitchen remodels replace sagging cabinets and stained countertops with quality new materials that transform the room. Bathroom updates replace one-piece fiberglass surrounds with custom tile, old vanities with modern designs, and dim lighting with bright, efficient fixtures. We also handle larger projects like manufactured home additions, deck construction, and full interior gut-renovations. For families considering a new modular home, we provide complete installation services including site work, foundation, set-up, and all finishing. Every project is completed to code, inspected, and warranted.",
    projectHighlights: [
      "Kitchen and bathroom remodel package for a manufactured home — complete transformation in 3 weeks",
      "24x12 covered deck addition with composite decking and vinyl railing",
      "Full manufactured home window replacement (14 windows) with energy-efficient vinyl units",
    ],
    whyUs: "We deliver manufactured home improvements that are practical, well-built, and fairly priced — because quality work shouldn't depend on your home's construction type.",
  },
];
